# Generated by Django 3.2.4 on 2021-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reportTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=30)),
                ('tasks', models.TextField()),
                ('code_commit', models.TextField(blank=True, null=True)),
                ('docs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
